# Generated by Django 4.2.7 on 2025-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_blogpost_contactmessage_sitesettings_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('step_type', models.CharField(choices=[('education', 'Formation'), ('experience', 'Expérience'), ('project', 'Projet'), ('achievement', 'Réalisation'), ('certification', 'Certification'), ('milestone', 'Étape importante')], default='experience', max_length=20, verbose_name="Type d'étape")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Étape actuelle')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('icon', models.CharField(default='fas fa-circle', max_length=50, verbose_name='Icône FontAwesome')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('image', models.ImageField(blank=True, null=True, upload_to='roadmap/', verbose_name='Image')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.technology', verbose_name='Compétences associées')),
            ],
            options={
                'verbose_name': 'Étape du parcours',
                'verbose_name_plural': 'Étapes du parcours',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
