# Generated by Django 4.2.7 on 2025-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_roadmapstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(default='fas fa-code', help_text='Icône FontAwesome (ex: fab fa-python)', max_length=50),
        ),
    ]
