# Generated by Django 4.2.7 on 2025-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_technology_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la certification')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Organisme émetteur')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID du certificat')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='URL du certificat')),
                ('issue_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Image du certificat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Mise en avant')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Vérifiée')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.technology', verbose_name='Compétences associées')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date', 'order'],
            },
        ),
    ]
