# Generated by Django 4.2.7 on 2025-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('devops', 'DevOps'), ('ai', 'Intelligence Artificielle'), ('other', 'Autre')], default='web', max_length=20),
        ),
    ]
